### ISSUE TITLE
Datepicker 'disappears' when choosing month or year, preventing date selection

### ISSUE THREAD

**Issue by mtmacdonald** [dbushell/Pikaday#230]
On branch master, using either Firefox or Internet Explorer (but not Chrome), it is not possible to use the month or year selectors. When clicking the month or year, the datepicker 'disappears', preventing selection. In fact, clicking anywhere outside one of the day buttons hides the datepicker.

The [demo page](http://dbushell.github.io/Pikaday) does not exhibit this issue, but appears to be a different, unspecified, version.

**Comment by bernhardh** [comment]
For me, this issue also appears on the demo page AND on chrome as well.

**Comment by rikkert** [comment]
Fixed

**Comment by mderazon** [comment]
Awesome library,
Love it when you download an open source project, encounter an issue and see that it was just fixed :+1: 

Can you please publish to npm / bower ?

Thanks !

**Comment by rikkert** [comment]
Consider it done.

**Comment by eliasib13** [comment]
I'm using this datepicker with Ionic Framework to incorporate it in my app, but I still have this problem: when I tap on it, the datepicker closes.

Another thing I've noticed is that when I tap on the picker (a day, a button, or whatever), the tap is caught by the datepicker (if I tap a day, the date is right selected; if I tap next month, when I reopen the picker it shows the next month), but also is caught as a tap on the page; so, for example, if I have a button behind the picker and I click the picker, the picker does what it should and also the button is clicked.

Maybe this can help to fix, and I'd be very thankful :+1:

**Comment by infacq** [comment]
this is still happening. You can test it on example `weeknumber.html`. I run it locally without web server on my pc

**Comment by rikkert** [comment]
try the latest released version.

**Comment by infacq** [comment]
i tried it with latest release

**Comment by dgwalton** [comment]
This issue occurs for me only on Windows 8.1 Chrome. All other browser/OS combinations work.

**Comment by skarkkai-p** [comment]
Happens for me with current Chrome but not Firefox, both on Ubuntu 14.04.

**Comment by goggledefogger** [comment]
Still happening for me too, Windows 8.1 Chrome. Any chance of another fix?
